CREATE SEQUENCE notification_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
NOCYCLE;

CREATE SEQUENCE rule_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
NOCYCLE;

CREATE SEQUENCE user_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
NOCYCLE;

CREATE SEQUENCE outbox_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;